# Generated by Django 2.1.7 on 2023-03-02 17:56

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_auto_20230302_1451'),
    ]

    operations = [
        migrations.AlterField(
            model_name='todo',
            name='created_at',
            field=models.DateField(blank=True, default=datetime.datetime(2023, 3, 2, 14, 56, 5, 968562)),
        ),
    ]
